export const GET_GENRES = "GET_GENRES"
export const GET_PLATFORMS = "GET_PLATFORMS"
export const SEARCH_VIDEOGAME = "SEARCH_VIDEOGAME"
export const GET_VIDEOGAME = "GET_VIDEOGAME"
export const GET_DETAILS = "GET_DETAILS"
export const PAGINATE = "PAGINATE "
export const FILTER_BY_GENRE = "FILTER_BY_GENRE"
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN "
export const RESET = "RESET"
export const ORD_ALFAB = "ORD_ALFAB";
export const ORD_RATING = "ORD_ALFAB";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const SET_PAGE = "SET_PAGE";
